from __future__ import annotations

import argparse
from collections import Counter
from pathlib import Path
from typing import Any, Dict, Iterable, List, Mapping

from v1_common import (
    DEFAULT_V1_1_DIR,
    DEFAULT_V1_DIR,
    PUBLIC_CASE_FORBIDDEN_FIELDS,
    RAW_EVENT_FIELDS,
    build_scope_profiles,
    read_json,
    write_json,
)


NEW_SPLIT_SCOPES = {
    "train": ["search_index_rollout", "billing_migration", "eval_harness"],
    "dev": ["cache_refactor"],
    "test": ["ui_accessibility", "api_rate_limit"],
}


EXPANSION_EVENTS: List[Dict[str, Any]] = [
    {
        "event_id": "idx_e1",
        "scope_id": "search_index_rollout",
        "content": "搜索索引项目最初决定上线 BM25 patch，并把 tokenizer v1 作为默认方案。",
        "event_type": "decision",
        "occurred_at": "2026-06-01T09:00:00",
        "mentioned_at": "2026-06-01T09:00:00",
        "updated_at": "2026-06-01T09:00:00",
        "planned_for": None,
        "deadline_at": None,
        "event_status": "superseded",
        "updates_state": True,
        "supersedes": [],
        "corrects": [],
    },
    {
        "event_id": "idx_e2",
        "scope_id": "search_index_rollout",
        "content": "线上抽样发现中文长查询召回下降，主要集中在 synonym expansion 后的多词问题。",
        "event_type": "issue",
        "occurred_at": "2026-06-02T10:00:00",
        "mentioned_at": "2026-06-02T10:00:00",
        "updated_at": "2026-06-02T10:00:00",
        "planned_for": None,
        "deadline_at": None,
        "event_status": "superseded",
        "updates_state": True,
        "supersedes": [],
        "corrects": [],
    },
    {
        "event_id": "idx_e3",
        "scope_id": "search_index_rollout",
        "content": "计划 6 月 6 日先部署 BM25 patch，再观察 recall dashboard。",
        "event_type": "plan",
        "occurred_at": "2026-06-03T09:30:00",
        "mentioned_at": "2026-06-03T09:30:00",
        "updated_at": "2026-06-03T09:30:00",
        "planned_for": "2026-06-06T09:00:00",
        "deadline_at": "2026-06-06T18:00:00",
        "event_status": "superseded",
        "updates_state": True,
        "supersedes": [],
        "corrects": [],
    },
    {
        "event_id": "idx_e4",
        "scope_id": "search_index_rollout",
        "content": "旧 dashboard 截图显示 BM25 patch 已经 rollout finished，但截图来自过期环境。",
        "event_type": "mention",
        "occurred_at": "2026-06-04T11:00:00",
        "mentioned_at": "2026-06-04T11:00:00",
        "updated_at": "2026-06-04T11:00:00",
        "planned_for": None,
        "deadline_at": None,
        "event_status": "historical_only",
        "updates_state": False,
        "supersedes": [],
        "corrects": [],
    },
    {
        "event_id": "idx_e5",
        "scope_id": "search_index_rollout",
        "content": "复盘确认 BM25 patch 没有部署，方案改为 hybrid sparse+dense 检索；旧 dashboard 截图作废。",
        "event_type": "correction",
        "occurred_at": "2026-06-05T16:00:00",
        "mentioned_at": "2026-06-05T16:00:00",
        "updated_at": "2026-06-05T16:00:00",
        "planned_for": None,
        "deadline_at": None,
        "event_status": "active",
        "updates_state": True,
        "supersedes": ["idx_e1", "idx_e3"],
        "corrects": ["idx_e4"],
    },
    {
        "event_id": "idx_e6",
        "scope_id": "search_index_rollout",
        "content": "hybrid 检索召回恢复，但 reranker p95 延迟超过预算 180ms。",
        "event_type": "issue",
        "occurred_at": "2026-06-06T17:00:00",
        "mentioned_at": "2026-06-06T17:00:00",
        "updated_at": "2026-06-06T17:00:00",
        "planned_for": None,
        "deadline_at": None,
        "event_status": "active",
        "updates_state": True,
        "supersedes": ["idx_e2"],
        "corrects": [],
    },
    {
        "event_id": "idx_e7",
        "scope_id": "search_index_rollout",
        "content": "下一步计划在 6 月 10 日评估更小的 cross-encoder，目前还没有完成记录。",
        "event_type": "plan",
        "occurred_at": "2026-06-07T10:00:00",
        "mentioned_at": "2026-06-07T10:00:00",
        "updated_at": "2026-06-07T10:00:00",
        "planned_for": "2026-06-10T10:00:00",
        "deadline_at": None,
        "event_status": "active",
        "updates_state": True,
        "supersedes": [],
        "corrects": [],
    },
    {
        "event_id": "idx_e8",
        "scope_id": "search_index_rollout",
        "content": "有人再次询问 BM25 patch 是否已经上线，回复是没有上线，只保留 hybrid 方向。",
        "event_type": "mention",
        "occurred_at": "2026-06-08T12:00:00",
        "mentioned_at": "2026-06-08T12:00:00",
        "updated_at": "2026-06-08T12:00:00",
        "planned_for": None,
        "deadline_at": None,
        "event_status": "active",
        "updates_state": False,
        "supersedes": [],
        "corrects": [],
    },
    {
        "event_id": "bill_e1",
        "scope_id": "billing_migration",
        "content": "Billing migration 最初决定把订阅计费迁到 Stripe。",
        "event_type": "decision",
        "occurred_at": "2026-06-01T13:00:00",
        "mentioned_at": "2026-06-01T13:00:00",
        "updated_at": "2026-06-01T13:00:00",
        "planned_for": None,
        "deadline_at": None,
        "event_status": "superseded",
        "updates_state": True,
        "supersedes": [],
        "corrects": [],
    },
    {
        "event_id": "bill_e2",
        "scope_id": "billing_migration",
        "content": "财务要求 6 月 12 日前确认本季度发票导出格式。",
        "event_type": "deadline",
        "occurred_at": "2026-06-02T09:00:00",
        "mentioned_at": "2026-06-02T09:00:00",
        "updated_at": "2026-06-02T09:00:00",
        "planned_for": None,
        "deadline_at": "2026-06-12T18:00:00",
        "event_status": "active",
        "updates_state": True,
        "supersedes": [],
        "corrects": [],
    },
    {
        "event_id": "bill_e3",
        "scope_id": "billing_migration",
        "content": "测试环境发现税费 rounding 和旧账单有 1-2 cent 偏差。",
        "event_type": "issue",
        "occurred_at": "2026-06-03T15:00:00",
        "mentioned_at": "2026-06-03T15:00:00",
        "updated_at": "2026-06-03T15:00:00",
        "planned_for": None,
        "deadline_at": None,
        "event_status": "active",
        "updates_state": True,
        "supersedes": [],
        "corrects": [],
    },
    {
        "event_id": "bill_e4",
        "scope_id": "billing_migration",
        "content": "企业合同限制导致 Stripe migration 被阻塞，团队转为评估 Paddle。",
        "event_type": "correction",
        "occurred_at": "2026-06-06T10:00:00",
        "mentioned_at": "2026-06-06T10:00:00",
        "updated_at": "2026-06-06T10:00:00",
        "planned_for": None,
        "deadline_at": None,
        "event_status": "superseded",
        "updates_state": True,
        "supersedes": ["bill_e1"],
        "corrects": [],
    },
    {
        "event_id": "bill_e5",
        "scope_id": "billing_migration",
        "content": "发票 CSV 导出已完成，但这只是财务报表导出，不代表计费 migration 已完成。",
        "event_type": "execution_log",
        "occurred_at": "2026-06-07T18:00:00",
        "mentioned_at": "2026-06-07T18:00:00",
        "updated_at": "2026-06-07T18:00:00",
        "planned_for": None,
        "deadline_at": None,
        "event_status": "active",
        "updates_state": True,
        "supersedes": [],
        "corrects": [],
    },
    {
        "event_id": "bill_e6",
        "scope_id": "billing_migration",
        "content": "旧迁移文档里写着 Stripe migration done，但文档没有同步企业合同限制。",
        "event_type": "mention",
        "occurred_at": "2026-06-08T09:00:00",
        "mentioned_at": "2026-06-08T09:00:00",
        "updated_at": "2026-06-08T09:00:00",
        "planned_for": None,
        "deadline_at": None,
        "event_status": "historical_only",
        "updates_state": False,
        "supersedes": [],
        "corrects": [],
    },
    {
        "event_id": "bill_e7",
        "scope_id": "billing_migration",
        "content": "最终决定暂时保留现有 provider，Paddle 只做 prototype，不进入生产迁移。",
        "event_type": "decision",
        "occurred_at": "2026-06-09T11:00:00",
        "mentioned_at": "2026-06-09T11:00:00",
        "updated_at": "2026-06-09T11:00:00",
        "planned_for": None,
        "deadline_at": None,
        "event_status": "active",
        "updates_state": True,
        "supersedes": ["bill_e4"],
        "corrects": ["bill_e6"],
    },
    {
        "event_id": "bill_e8",
        "scope_id": "billing_migration",
        "content": "下一步安排 6 月 13 日做 legal review，目前没有 review 完成记录。",
        "event_type": "plan",
        "occurred_at": "2026-06-10T16:00:00",
        "mentioned_at": "2026-06-10T16:00:00",
        "updated_at": "2026-06-10T16:00:00",
        "planned_for": "2026-06-13T10:00:00",
        "deadline_at": None,
        "event_status": "active",
        "updates_state": True,
        "supersedes": [],
        "corrects": [],
    },
    {
        "event_id": "eval_e1",
        "scope_id": "eval_harness",
        "content": "评测脚本最初只按 event_f1 给方法排序。",
        "event_type": "decision",
        "occurred_at": "2026-06-01T10:00:00",
        "mentioned_at": "2026-06-01T10:00:00",
        "updated_at": "2026-06-01T10:00:00",
        "planned_for": None,
        "deadline_at": None,
        "event_status": "superseded",
        "updates_state": True,
        "supersedes": [],
        "corrects": [],
    },
    {
        "event_id": "eval_e2",
        "scope_id": "eval_harness",
        "content": "正式实验约定 DeepSeek 用来回答，GPT judge 用来语义评分。",
        "event_type": "decision",
        "occurred_at": "2026-06-02T10:00:00",
        "mentioned_at": "2026-06-02T10:00:00",
        "updated_at": "2026-06-02T10:00:00",
        "planned_for": None,
        "deadline_at": None,
        "event_status": "active",
        "updates_state": True,
        "supersedes": [],
        "corrects": [],
    },
    {
        "event_id": "eval_e3",
        "scope_id": "eval_harness",
        "content": "任务定义冻结：主排序看 sup_f1、slot_j、ans_j，event_f1 只作为诊断。",
        "event_type": "decision",
        "occurred_at": "2026-06-03T14:00:00",
        "mentioned_at": "2026-06-03T14:00:00",
        "updated_at": "2026-06-03T14:00:00",
        "planned_for": None,
        "deadline_at": None,
        "event_status": "active",
        "updates_state": True,
        "supersedes": ["eval_e1"],
        "corrects": [],
    },
    {
        "event_id": "eval_e4",
        "scope_id": "eval_harness",
        "content": "Graphiti 还有 3 个 judge hole，Validity-aware 还有 2 个 judge hole。",
        "event_type": "issue",
        "occurred_at": "2026-06-04T12:00:00",
        "mentioned_at": "2026-06-04T12:00:00",
        "updated_at": "2026-06-04T12:00:00",
        "planned_for": None,
        "deadline_at": None,
        "event_status": "superseded",
        "updates_state": True,
        "supersedes": [],
        "corrects": [],
    },
    {
        "event_id": "eval_e5",
        "scope_id": "eval_harness",
        "content": "重新跑 judge 后主表所有方法都达到 42/42 judge coverage。",
        "event_type": "execution_log",
        "occurred_at": "2026-06-05T19:00:00",
        "mentioned_at": "2026-06-05T19:00:00",
        "updated_at": "2026-06-05T19:00:00",
        "planned_for": None,
        "deadline_at": None,
        "event_status": "active",
        "updates_state": True,
        "supersedes": [],
        "corrects": ["eval_e4"],
    },
    {
        "event_id": "eval_e6",
        "scope_id": "eval_harness",
        "content": "会议纪要里有人仍说 event_f1 第一就代表最好，但这是旧口径。",
        "event_type": "mention",
        "occurred_at": "2026-06-06T09:00:00",
        "mentioned_at": "2026-06-06T09:00:00",
        "updated_at": "2026-06-06T09:00:00",
        "planned_for": None,
        "deadline_at": None,
        "event_status": "historical_only",
        "updates_state": False,
        "supersedes": [],
        "corrects": [],
    },
    {
        "event_id": "eval_e7",
        "scope_id": "eval_harness",
        "content": "下一步计划给 v1.1 增加 over-evidence rate 和 unknown-current accuracy 诊断，还没有正式实现。",
        "event_type": "plan",
        "occurred_at": "2026-06-07T16:00:00",
        "mentioned_at": "2026-06-07T16:00:00",
        "updated_at": "2026-06-07T16:00:00",
        "planned_for": "2026-06-09T10:00:00",
        "deadline_at": None,
        "event_status": "active",
        "updates_state": True,
        "supersedes": [],
        "corrects": [],
    },
    {
        "event_id": "eval_e8",
        "scope_id": "eval_harness",
        "content": "当前主要风险是扩 benchmark 时不小心过拟合 Ours，而不是只追求更高分。",
        "event_type": "risk",
        "occurred_at": "2026-06-08T11:00:00",
        "mentioned_at": "2026-06-08T11:00:00",
        "updated_at": "2026-06-08T11:00:00",
        "planned_for": None,
        "deadline_at": None,
        "event_status": "active",
        "updates_state": True,
        "supersedes": [],
        "corrects": [],
    },
    {
        "event_id": "cache_e1",
        "scope_id": "cache_refactor",
        "content": "LLM cache 会返回同一个 parsed object，后续 trace mutation 可能污染缓存。",
        "event_type": "issue",
        "occurred_at": "2026-06-01T15:00:00",
        "mentioned_at": "2026-06-01T15:00:00",
        "updated_at": "2026-06-01T15:00:00",
        "planned_for": None,
        "deadline_at": None,
        "event_status": "superseded",
        "updates_state": True,
        "supersedes": [],
        "corrects": [],
    },
    {
        "event_id": "cache_e2",
        "scope_id": "cache_refactor",
        "content": "修复 cache：命中、写入和返回都使用 deepcopy，并改为 transactional write。",
        "event_type": "fix",
        "occurred_at": "2026-06-02T12:00:00",
        "mentioned_at": "2026-06-02T12:00:00",
        "updated_at": "2026-06-02T12:00:00",
        "planned_for": None,
        "deadline_at": None,
        "event_status": "active",
        "updates_state": True,
        "supersedes": [],
        "corrects": ["cache_e1"],
    },
    {
        "event_id": "cache_e3",
        "scope_id": "cache_refactor",
        "content": "Graphiti verifier trace 把 raw 自身写入 pipeline_trace，导致 JSON dump 出现 circular reference。",
        "event_type": "issue",
        "occurred_at": "2026-06-03T10:00:00",
        "mentioned_at": "2026-06-03T10:00:00",
        "updated_at": "2026-06-03T10:00:00",
        "planned_for": None,
        "deadline_at": None,
        "event_status": "superseded",
        "updates_state": True,
        "supersedes": [],
        "corrects": [],
    },
    {
        "event_id": "cache_e4",
        "scope_id": "cache_refactor",
        "content": "修复 Graphiti trace：draft 和 verifier output 先 deepcopy，再写入 pipeline_trace。",
        "event_type": "fix",
        "occurred_at": "2026-06-04T10:00:00",
        "mentioned_at": "2026-06-04T10:00:00",
        "updated_at": "2026-06-04T10:00:00",
        "planned_for": None,
        "deadline_at": None,
        "event_status": "active",
        "updates_state": True,
        "supersedes": [],
        "corrects": ["cache_e3"],
    },
    {
        "event_id": "cache_e5",
        "scope_id": "cache_refactor",
        "content": "py_compile 验证时重新生成了 Experiment 下的 __pycache__。",
        "event_type": "execution_log",
        "occurred_at": "2026-06-05T09:00:00",
        "mentioned_at": "2026-06-05T09:00:00",
        "updated_at": "2026-06-05T09:00:00",
        "planned_for": None,
        "deadline_at": None,
        "event_status": "superseded",
        "updates_state": False,
        "supersedes": [],
        "corrects": [],
    },
    {
        "event_id": "cache_e6",
        "scope_id": "cache_refactor",
        "content": "__pycache__ 已经清理，Experiment 目录没有残留运行产物。",
        "event_type": "cleanup",
        "occurred_at": "2026-06-05T09:30:00",
        "mentioned_at": "2026-06-05T09:30:00",
        "updated_at": "2026-06-05T09:30:00",
        "planned_for": None,
        "deadline_at": None,
        "event_status": "active",
        "updates_state": True,
        "supersedes": ["cache_e5"],
        "corrects": [],
    },
    {
        "event_id": "cache_e7",
        "scope_id": "cache_refactor",
        "content": "计划之后补一个 cache mutation regression test，但目前还没有测试落地记录。",
        "event_type": "plan",
        "occurred_at": "2026-06-06T11:00:00",
        "mentioned_at": "2026-06-06T11:00:00",
        "updated_at": "2026-06-06T11:00:00",
        "planned_for": "2026-06-08T10:00:00",
        "deadline_at": None,
        "event_status": "active",
        "updates_state": True,
        "supersedes": [],
        "corrects": [],
    },
    {
        "event_id": "cache_e8",
        "scope_id": "cache_refactor",
        "content": "旧错误日志还写着 circular reference 未解决，但日志时间早于 trace deepcopy fix。",
        "event_type": "mention",
        "occurred_at": "2026-06-07T08:00:00",
        "mentioned_at": "2026-06-07T08:00:00",
        "updated_at": "2026-06-07T08:00:00",
        "planned_for": None,
        "deadline_at": None,
        "event_status": "historical_only",
        "updates_state": False,
        "supersedes": [],
        "corrects": [],
    },
    {
        "event_id": "ui_e1",
        "scope_id": "ui_accessibility",
        "content": "前端初版使用大卡片布局，并计划保留装饰性渐变背景。",
        "event_type": "decision",
        "occurred_at": "2026-06-01T10:00:00",
        "mentioned_at": "2026-06-01T10:00:00",
        "updated_at": "2026-06-01T10:00:00",
        "planned_for": None,
        "deadline_at": None,
        "event_status": "superseded",
        "updates_state": True,
        "supersedes": [],
        "corrects": [],
    },
    {
        "event_id": "ui_e2",
        "scope_id": "ui_accessibility",
        "content": "移动端 QA 发现 toolbar 文本会和后续控件重叠。",
        "event_type": "issue",
        "occurred_at": "2026-06-02T14:00:00",
        "mentioned_at": "2026-06-02T14:00:00",
        "updated_at": "2026-06-02T14:00:00",
        "planned_for": None,
        "deadline_at": None,
        "event_status": "superseded",
        "updates_state": True,
        "supersedes": [],
        "corrects": [],
    },
    {
        "event_id": "ui_e3",
        "scope_id": "ui_accessibility",
        "content": "计划用 responsive constraints 修 toolbar，并在 6 月 4 日回归移动端。",
        "event_type": "plan",
        "occurred_at": "2026-06-03T09:00:00",
        "mentioned_at": "2026-06-03T09:00:00",
        "updated_at": "2026-06-03T09:00:00",
        "planned_for": "2026-06-04T12:00:00",
        "deadline_at": None,
        "event_status": "superseded",
        "updates_state": True,
        "supersedes": [],
        "corrects": [],
    },
    {
        "event_id": "ui_e4",
        "scope_id": "ui_accessibility",
        "content": "toolbar label wrapping 和固定尺寸已修复，移动端不再重叠。",
        "event_type": "fix",
        "occurred_at": "2026-06-04T15:00:00",
        "mentioned_at": "2026-06-04T15:00:00",
        "updated_at": "2026-06-04T15:00:00",
        "planned_for": None,
        "deadline_at": None,
        "event_status": "active",
        "updates_state": True,
        "supersedes": ["ui_e2", "ui_e3"],
        "corrects": [],
    },
    {
        "event_id": "ui_e5",
        "scope_id": "ui_accessibility",
        "content": "二级按钮 contrast 仍低于目标，需要重新调色。",
        "event_type": "issue",
        "occurred_at": "2026-06-05T11:00:00",
        "mentioned_at": "2026-06-05T11:00:00",
        "updated_at": "2026-06-05T11:00:00",
        "planned_for": None,
        "deadline_at": None,
        "event_status": "active",
        "updates_state": True,
        "supersedes": [],
        "corrects": [],
    },
    {
        "event_id": "ui_e6",
        "scope_id": "ui_accessibility",
        "content": "群里转发旧截图，说 toolbar 仍然重叠，但截图来自修复前。",
        "event_type": "mention",
        "occurred_at": "2026-06-06T09:30:00",
        "mentioned_at": "2026-06-06T09:30:00",
        "updated_at": "2026-06-06T09:30:00",
        "planned_for": None,
        "deadline_at": None,
        "event_status": "historical_only",
        "updates_state": False,
        "supersedes": [],
        "corrects": [],
    },
    {
        "event_id": "ui_e7",
        "scope_id": "ui_accessibility",
        "content": "设计决定删掉装饰性渐变背景，按钮使用功能性图标和更克制的布局。",
        "event_type": "decision",
        "occurred_at": "2026-06-07T10:00:00",
        "mentioned_at": "2026-06-07T10:00:00",
        "updated_at": "2026-06-07T10:00:00",
        "planned_for": None,
        "deadline_at": None,
        "event_status": "active",
        "updates_state": True,
        "supersedes": ["ui_e1"],
        "corrects": [],
    },
    {
        "event_id": "ui_e8",
        "scope_id": "ui_accessibility",
        "content": "计划 6 月 10 日做最终 mobile accessibility audit，目前还没有 audit 完成记录。",
        "event_type": "plan",
        "occurred_at": "2026-06-08T16:00:00",
        "mentioned_at": "2026-06-08T16:00:00",
        "updated_at": "2026-06-08T16:00:00",
        "planned_for": "2026-06-10T09:00:00",
        "deadline_at": None,
        "event_status": "active",
        "updates_state": True,
        "supersedes": [],
        "corrects": [],
    },
    {
        "event_id": "api_e1",
        "scope_id": "api_rate_limit",
        "content": "实验最初计划用 DeepSeek 回答、GPT judge 评分。",
        "event_type": "decision",
        "occurred_at": "2026-06-01T10:00:00",
        "mentioned_at": "2026-06-01T10:00:00",
        "updated_at": "2026-06-01T10:00:00",
        "planned_for": None,
        "deadline_at": None,
        "event_status": "active",
        "updates_state": True,
        "supersedes": [],
        "corrects": [],
    },
    {
        "event_id": "api_e2",
        "scope_id": "api_rate_limit",
        "content": "全量构图时 DeepSeek 额度不稳定，Graphiti ingestion 需要换到 OpenAI-compatible provider。",
        "event_type": "issue",
        "occurred_at": "2026-06-02T12:00:00",
        "mentioned_at": "2026-06-02T12:00:00",
        "updated_at": "2026-06-02T12:00:00",
        "planned_for": None,
        "deadline_at": None,
        "event_status": "superseded",
        "updates_state": True,
        "supersedes": [],
        "corrects": [],
    },
    {
        "event_id": "api_e3",
        "scope_id": "api_rate_limit",
        "content": "决定 Graphiti 构图使用 OpenAI-compatible provider，回答仍用 DeepSeek，judge 仍用 GPT。",
        "event_type": "decision",
        "occurred_at": "2026-06-03T13:00:00",
        "mentioned_at": "2026-06-03T13:00:00",
        "updated_at": "2026-06-03T13:00:00",
        "planned_for": None,
        "deadline_at": None,
        "event_status": "active",
        "updates_state": True,
        "supersedes": ["api_e2"],
        "corrects": [],
    },
    {
        "event_id": "api_e4",
        "scope_id": "api_rate_limit",
        "content": "旧日志显示 OpenAI-compatible endpoint token invalid。",
        "event_type": "mention",
        "occurred_at": "2026-06-04T09:00:00",
        "mentioned_at": "2026-06-04T09:00:00",
        "updated_at": "2026-06-04T09:00:00",
        "planned_for": None,
        "deadline_at": None,
        "event_status": "historical_only",
        "updates_state": False,
        "supersedes": [],
        "corrects": [],
    },
    {
        "event_id": "api_e5",
        "scope_id": "api_rate_limit",
        "content": "最小 API ping 已通过，说明 endpoint 当前可用。",
        "event_type": "fix",
        "occurred_at": "2026-06-05T10:00:00",
        "mentioned_at": "2026-06-05T10:00:00",
        "updated_at": "2026-06-05T10:00:00",
        "planned_for": None,
        "deadline_at": None,
        "event_status": "active",
        "updates_state": True,
        "supersedes": [],
        "corrects": ["api_e4"],
    },
    {
        "event_id": "api_e6",
        "scope_id": "api_rate_limit",
        "content": "计划用可用 endpoint 重建 Graphiti 图。",
        "event_type": "plan",
        "occurred_at": "2026-06-06T10:00:00",
        "mentioned_at": "2026-06-06T10:00:00",
        "updated_at": "2026-06-06T10:00:00",
        "planned_for": "2026-06-06T14:00:00",
        "deadline_at": None,
        "event_status": "superseded",
        "updates_state": True,
        "supersedes": [],
        "corrects": [],
    },
    {
        "event_id": "api_e7",
        "scope_id": "api_rate_limit",
        "content": "Graphiti 全量 run 已完成 42 个 case，并写出 repaired adapter 结果。",
        "event_type": "execution_log",
        "occurred_at": "2026-06-06T20:00:00",
        "mentioned_at": "2026-06-06T20:00:00",
        "updated_at": "2026-06-06T20:00:00",
        "planned_for": None,
        "deadline_at": None,
        "event_status": "active",
        "updates_state": True,
        "supersedes": ["api_e6"],
        "corrects": [],
    },
    {
        "event_id": "api_e8",
        "scope_id": "api_rate_limit",
        "content": "剩余风险是 judge 调用成本和 endpoint 抖动，所以后续实验要保留 cache。",
        "event_type": "risk",
        "occurred_at": "2026-06-07T12:00:00",
        "mentioned_at": "2026-06-07T12:00:00",
        "updated_at": "2026-06-07T12:00:00",
        "planned_for": None,
        "deadline_at": None,
        "event_status": "active",
        "updates_state": True,
        "supersedes": [],
        "corrects": [],
    },
]


EXPANSION_CASES: List[Dict[str, Any]] = [
    {
        "case_id": "idx_status",
        "query": "搜索索引现在是什么状态？",
        "scope_id": "search_index_rollout",
        "operation": "state_summary",
        "time_roles": ["updated_at"],
        "difficulty_tags": ["latest_event_vs_state", "stale_mention_distractor", "correction_aware", "multi_facet_summary", "cross_time_constraint"],
        "gold_events": ["idx_e5", "idx_e6", "idx_e7"],
        "hard_negative_events": ["idx_e4", "idx_e3", "idx_e8"],
        "gold_state_slots": {
            "current_strategy": "BM25 patch 没有部署，当前转为 hybrid sparse+dense 检索方向",
            "current_issue": "reranker p95 延迟超过 180ms 预算",
            "next_step": "评估更小的 cross-encoder，但还没有完成记录",
        },
        "gold_slot_support": {
            "current_strategy": ["idx_e5"],
            "current_issue": ["idx_e6"],
            "next_step": ["idx_e7"],
        },
        "output_slots": ["current_strategy", "current_issue", "next_step"],
        "answerability": "answerable",
    },
    {
        "case_id": "idx_completion_unknown",
        "query": "小 cross-encoder 评估完成了吗？",
        "scope_id": "search_index_rollout",
        "operation": "state_lookup",
        "time_roles": ["planned_for", "updated_at"],
        "difficulty_tags": ["unknown_current", "plan_not_done", "cross_time_constraint"],
        "gold_events": ["idx_e7"],
        "hard_negative_events": ["idx_e4", "idx_e8"],
        "gold_state_slots": {
            "completion_status": "只有评估计划，没有完成记录",
        },
        "gold_slot_support": {
            "completion_status": ["idx_e7"],
        },
        "output_slots": ["completion_status"],
        "answerability": "unknown_current",
    },
    {
        "case_id": "idx_invalid_rollout",
        "query": "BM25 patch 现在还是上线计划吗？",
        "scope_id": "search_index_rollout",
        "operation": "state_lookup",
        "time_roles": ["updated_at"],
        "difficulty_tags": ["facet_specific_validity", "correction_aware", "stale_mention_distractor"],
        "gold_events": ["idx_e3", "idx_e5"],
        "hard_negative_events": ["idx_e4", "idx_e8"],
        "gold_state_slots": {
            "bm25_plan_status": "BM25 patch 上线计划已作废，没有部署",
            "replacement": "替代方向是 hybrid sparse+dense 检索",
        },
        "gold_slot_support": {
            "bm25_plan_status": ["idx_e3", "idx_e5"],
            "replacement": ["idx_e5"],
        },
        "output_slots": ["bm25_plan_status", "replacement"],
        "answerability": "answerable",
    },
    {
        "case_id": "idx_latency_issue",
        "query": "搜索索引现在还卡在哪里？",
        "scope_id": "search_index_rollout",
        "operation": "state_lookup",
        "time_roles": ["updated_at"],
        "difficulty_tags": ["latest_event_vs_state", "non_update_latest"],
        "gold_events": ["idx_e6"],
        "hard_negative_events": ["idx_e8", "idx_e2"],
        "gold_state_slots": {
            "current_blocker": "hybrid 召回恢复后，当前 blocker 是 reranker p95 延迟超过预算",
        },
        "gold_slot_support": {
            "current_blocker": ["idx_e6"],
        },
        "output_slots": ["current_blocker"],
        "answerability": "answerable",
    },
    {
        "case_id": "idx_actual_vs_mentioned",
        "query": "6 月 4 日那张 dashboard 说 rollout finished，可以相信吗？",
        "scope_id": "search_index_rollout",
        "operation": "state_lookup",
        "time_roles": ["mentioned_at", "updated_at"],
        "difficulty_tags": ["mentioned_vs_actual_conflict", "stale_mention_distractor", "correction_aware"],
        "gold_events": ["idx_e4", "idx_e5"],
        "hard_negative_events": ["idx_e8"],
        "gold_state_slots": {
            "dashboard_claim_status": "不能相信；旧 dashboard 截图来自过期环境，已被复盘纠正",
        },
        "gold_slot_support": {
            "dashboard_claim_status": ["idx_e4", "idx_e5"],
        },
        "output_slots": ["dashboard_claim_status"],
        "answerability": "answerable",
    },
    {
        "case_id": "bill_status",
        "query": "billing migration 最近怎么样？",
        "scope_id": "billing_migration",
        "operation": "state_summary",
        "time_roles": ["updated_at"],
        "difficulty_tags": ["branch_pivot", "facet_specific_validity", "multi_facet_summary", "stale_mention_distractor"],
        "gold_events": ["bill_e3", "bill_e4", "bill_e7", "bill_e8"],
        "hard_negative_events": ["bill_e6", "bill_e1"],
        "gold_state_slots": {
            "provider_strategy": "暂时保留现有 provider，Paddle 只做 prototype，不进入生产迁移",
            "current_issue": "税费 rounding 和旧账单仍有 1-2 cent 偏差",
            "next_step": "安排 legal review，但还没有完成记录",
        },
        "gold_slot_support": {
            "provider_strategy": ["bill_e4", "bill_e7"],
            "current_issue": ["bill_e3"],
            "next_step": ["bill_e8"],
        },
        "output_slots": ["provider_strategy", "current_issue", "next_step"],
        "answerability": "answerable",
    },
    {
        "case_id": "bill_provider",
        "query": "现在 billing 要迁到 Stripe 还是 Paddle？",
        "scope_id": "billing_migration",
        "operation": "state_lookup",
        "time_roles": ["updated_at"],
        "difficulty_tags": ["branch_pivot", "correction_aware", "stale_mention_distractor"],
        "gold_events": ["bill_e1", "bill_e4", "bill_e7"],
        "hard_negative_events": ["bill_e6"],
        "gold_state_slots": {
            "stripe_status": "Stripe migration 已被企业合同限制阻塞，不是当前生产迁移方向",
            "paddle_status": "Paddle 只做 prototype，生产上暂时保留现有 provider",
        },
        "gold_slot_support": {
            "stripe_status": ["bill_e1", "bill_e4", "bill_e7"],
            "paddle_status": ["bill_e4", "bill_e7"],
        },
        "output_slots": ["stripe_status", "paddle_status"],
        "answerability": "answerable",
    },
    {
        "case_id": "bill_invoice_confusion",
        "query": "发票 CSV 做完是不是代表 billing migration 完成了？",
        "scope_id": "billing_migration",
        "operation": "state_lookup",
        "time_roles": ["updated_at"],
        "difficulty_tags": ["non_update_latest", "scope_facet_collision", "latest_event_vs_state"],
        "gold_events": ["bill_e5", "bill_e7"],
        "hard_negative_events": ["bill_e6", "bill_e1"],
        "gold_state_slots": {
            "migration_completion": "不能这么理解；CSV 导出完成只是财务报表导出，生产计费 migration 没有完成",
        },
        "gold_slot_support": {
            "migration_completion": ["bill_e5", "bill_e7"],
        },
        "output_slots": ["migration_completion"],
        "answerability": "answerable",
    },
    {
        "case_id": "bill_legal_unknown",
        "query": "legal review 做完了吗？",
        "scope_id": "billing_migration",
        "operation": "state_lookup",
        "time_roles": ["planned_for", "updated_at"],
        "difficulty_tags": ["unknown_current", "plan_not_done", "cross_time_constraint"],
        "gold_events": ["bill_e8"],
        "hard_negative_events": ["bill_e5", "bill_e6"],
        "gold_state_slots": {
            "legal_review_status": "只有 legal review 安排，没有完成记录",
        },
        "gold_slot_support": {
            "legal_review_status": ["bill_e8"],
        },
        "output_slots": ["legal_review_status"],
        "answerability": "unknown_current",
    },
    {
        "case_id": "bill_deadline",
        "query": "billing 这边现在最近的明确 deadline 是什么？",
        "scope_id": "billing_migration",
        "operation": "next_action",
        "time_roles": ["deadline_at", "updated_at"],
        "difficulty_tags": ["deadline_change", "cross_time_constraint"],
        "gold_events": ["bill_e2"],
        "hard_negative_events": ["bill_e8"],
        "gold_state_slots": {
            "deadline": "6 月 12 日前确认本季度发票导出格式",
        },
        "gold_slot_support": {
            "deadline": ["bill_e2"],
        },
        "output_slots": ["deadline"],
        "answerability": "answerable",
    },
    {
        "case_id": "eval_primary_metrics",
        "query": "现在主表到底按什么指标判断方法？",
        "scope_id": "eval_harness",
        "operation": "state_lookup",
        "time_roles": ["updated_at"],
        "difficulty_tags": ["facet_specific_validity", "correction_aware", "metric_semantics"],
        "gold_events": ["eval_e1", "eval_e3"],
        "hard_negative_events": ["eval_e6"],
        "gold_state_slots": {
            "primary_metrics": "主排序看 sup_f1、slot_j、ans_j",
            "diagnostic_metric": "event_f1 只作为诊断，不单独决定方法优劣",
        },
        "gold_slot_support": {
            "primary_metrics": ["eval_e3"],
            "diagnostic_metric": ["eval_e1", "eval_e3"],
        },
        "output_slots": ["primary_metrics", "diagnostic_metric"],
        "answerability": "answerable",
    },
    {
        "case_id": "eval_judge_coverage",
        "query": "现在主表 judge coverage 还有洞吗？",
        "scope_id": "eval_harness",
        "operation": "state_lookup",
        "time_roles": ["updated_at"],
        "difficulty_tags": ["latest_event_vs_state", "correction_aware"],
        "gold_events": ["eval_e4", "eval_e5"],
        "hard_negative_events": ["eval_e6"],
        "gold_state_slots": {
            "judge_coverage": "之前有 Graphiti 3 个和 Validity-aware 2 个 judge hole，现在主表所有方法都是 42/42",
        },
        "gold_slot_support": {
            "judge_coverage": ["eval_e4", "eval_e5"],
        },
        "output_slots": ["judge_coverage"],
        "answerability": "answerable",
    },
    {
        "case_id": "eval_next_diag",
        "query": "v1.1 新诊断指标实现了吗？",
        "scope_id": "eval_harness",
        "operation": "state_lookup",
        "time_roles": ["planned_for", "updated_at"],
        "difficulty_tags": ["unknown_current", "plan_not_done", "metric_semantics"],
        "gold_events": ["eval_e7"],
        "hard_negative_events": ["eval_e3"],
        "gold_state_slots": {
            "diagnostic_status": "over-evidence rate 和 unknown-current accuracy 只是计划加入，还没有正式实现",
        },
        "gold_slot_support": {
            "diagnostic_status": ["eval_e7"],
        },
        "output_slots": ["diagnostic_status"],
        "answerability": "unknown_current",
    },
    {
        "case_id": "eval_overfit_risk",
        "query": "扩 benchmark 最大风险是什么？",
        "scope_id": "eval_harness",
        "operation": "state_lookup",
        "time_roles": ["updated_at"],
        "difficulty_tags": ["benchmark_bias_guard", "latest_event_vs_state"],
        "gold_events": ["eval_e8"],
        "hard_negative_events": ["eval_e6"],
        "gold_state_slots": {
            "risk": "扩 benchmark 时不小心过拟合 Ours，而不是只追求更高分",
        },
        "gold_slot_support": {
            "risk": ["eval_e8"],
        },
        "output_slots": ["risk"],
        "answerability": "answerable",
    },
    {
        "case_id": "eval_event_f1_only",
        "query": "如果一个方法 event_f1 最高，现在能直接说它最好吗？",
        "scope_id": "eval_harness",
        "operation": "state_lookup",
        "time_roles": ["updated_at"],
        "difficulty_tags": ["stale_mention_distractor", "metric_semantics", "correction_aware"],
        "gold_events": ["eval_e1", "eval_e3", "eval_e6"],
        "hard_negative_events": [],
        "gold_state_slots": {
            "ranking_rule": "不能；event_f1 第一是旧口径，当前要看 sup_f1、slot_j、ans_j",
        },
        "gold_slot_support": {
            "ranking_rule": ["eval_e1", "eval_e3", "eval_e6"],
        },
        "output_slots": ["ranking_rule"],
        "answerability": "answerable",
    },
    {
        "case_id": "cache_status",
        "query": "cache/refactor 现在状态怎样？",
        "scope_id": "cache_refactor",
        "operation": "state_summary",
        "time_roles": ["updated_at"],
        "difficulty_tags": ["correction_aware", "multi_facet_summary", "plan_not_done"],
        "gold_events": ["cache_e1", "cache_e2", "cache_e3", "cache_e4", "cache_e7"],
        "hard_negative_events": ["cache_e8", "cache_e5"],
        "gold_state_slots": {
            "cache_fix": "cache 已通过 deepcopy 和 transactional write 修复",
            "trace_fix": "Graphiti trace 已通过 deepcopy draft/verifier output 修复 circular reference",
            "remaining_work": "cache mutation regression test 还只是计划，没有落地记录",
        },
        "gold_slot_support": {
            "cache_fix": ["cache_e1", "cache_e2"],
            "trace_fix": ["cache_e3", "cache_e4"],
            "remaining_work": ["cache_e7"],
        },
        "output_slots": ["cache_fix", "trace_fix", "remaining_work"],
        "answerability": "answerable",
    },
    {
        "case_id": "cache_bug_fixed",
        "query": "circular reference 问题解决了吗？",
        "scope_id": "cache_refactor",
        "operation": "state_lookup",
        "time_roles": ["updated_at"],
        "difficulty_tags": ["correction_aware", "stale_mention_distractor"],
        "gold_events": ["cache_e3", "cache_e4"],
        "hard_negative_events": ["cache_e8"],
        "gold_state_slots": {
            "circular_ref_status": "已解决；trace 写入前会 deepcopy draft 和 verifier output",
        },
        "gold_slot_support": {
            "circular_ref_status": ["cache_e3", "cache_e4"],
        },
        "output_slots": ["circular_ref_status"],
        "answerability": "answerable",
    },
    {
        "case_id": "cache_cleanup",
        "query": "Experiment 目录现在还有 __pycache__ 吗？",
        "scope_id": "cache_refactor",
        "operation": "state_lookup",
        "time_roles": ["updated_at"],
        "difficulty_tags": ["latest_event_vs_state", "non_update_latest"],
        "gold_events": ["cache_e5", "cache_e6"],
        "hard_negative_events": [],
        "gold_state_slots": {
            "pycache_status": "__pycache__ 曾由 py_compile 生成，但之后已经清理，Experiment 目录没有残留运行产物",
        },
        "gold_slot_support": {
            "pycache_status": ["cache_e5", "cache_e6"],
        },
        "output_slots": ["pycache_status"],
        "answerability": "answerable",
    },
    {
        "case_id": "cache_test_unknown",
        "query": "cache mutation regression test 已经补了吗？",
        "scope_id": "cache_refactor",
        "operation": "state_lookup",
        "time_roles": ["planned_for", "updated_at"],
        "difficulty_tags": ["unknown_current", "plan_not_done"],
        "gold_events": ["cache_e7"],
        "hard_negative_events": ["cache_e2", "cache_e4"],
        "gold_state_slots": {
            "regression_test_status": "只有补测试计划，没有测试落地记录",
        },
        "gold_slot_support": {
            "regression_test_status": ["cache_e7"],
        },
        "output_slots": ["regression_test_status"],
        "answerability": "unknown_current",
    },
    {
        "case_id": "cache_prod_rollout_insufficient",
        "query": "这个 cache/refactor 修复已经上线 production 了吗？",
        "scope_id": "cache_refactor",
        "operation": "state_lookup",
        "time_roles": ["updated_at"],
        "difficulty_tags": ["insufficient_evidence", "answerability"],
        "gold_events": [],
        "hard_negative_events": ["cache_e2", "cache_e4"],
        "gold_state_slots": {
            "production_rollout": "没有足够证据确认已经上线 production",
        },
        "gold_slot_support": {
            "production_rollout": [],
        },
        "output_slots": ["production_rollout"],
        "answerability": "insufficient_evidence",
    },
    {
        "case_id": "ui_status",
        "query": "UI accessibility 现在还有什么问题？",
        "scope_id": "ui_accessibility",
        "operation": "state_summary",
        "time_roles": ["updated_at"],
        "difficulty_tags": ["multi_facet_summary", "stale_mention_distractor", "plan_not_done"],
        "gold_events": ["ui_e1", "ui_e2", "ui_e4", "ui_e5", "ui_e7", "ui_e8"],
        "hard_negative_events": ["ui_e6"],
        "gold_state_slots": {
            "fixed_issue": "toolbar label wrapping 和固定尺寸已修复，移动端不再重叠",
            "remaining_issue": "二级按钮 contrast 仍低于目标",
            "visual_policy": "删掉装饰性渐变背景，使用功能性图标和克制布局",
            "next_step": "最终 mobile accessibility audit 还只是计划，没有完成记录",
        },
        "gold_slot_support": {
            "fixed_issue": ["ui_e2", "ui_e4"],
            "remaining_issue": ["ui_e5"],
            "visual_policy": ["ui_e1", "ui_e7"],
            "next_step": ["ui_e8"],
        },
        "output_slots": ["fixed_issue", "remaining_issue", "visual_policy", "next_step"],
        "answerability": "answerable",
    },
    {
        "case_id": "ui_overlap_current",
        "query": "移动端 toolbar 现在还重叠吗？",
        "scope_id": "ui_accessibility",
        "operation": "state_lookup",
        "time_roles": ["updated_at"],
        "difficulty_tags": ["correction_aware", "stale_mention_distractor", "latest_event_vs_state"],
        "gold_events": ["ui_e2", "ui_e4", "ui_e6"],
        "hard_negative_events": [],
        "gold_state_slots": {
            "overlap_status": "不再重叠；旧截图来自修复前，当前 toolbar wrapping 和固定尺寸已修复",
        },
        "gold_slot_support": {
            "overlap_status": ["ui_e2", "ui_e4", "ui_e6"],
        },
        "output_slots": ["overlap_status"],
        "answerability": "answerable",
    },
    {
        "case_id": "ui_contrast_issue",
        "query": "UI 当前还没解决的 accessibility 问题是什么？",
        "scope_id": "ui_accessibility",
        "operation": "state_lookup",
        "time_roles": ["updated_at"],
        "difficulty_tags": ["latest_event_vs_state", "facet_specific_validity"],
        "gold_events": ["ui_e5"],
        "hard_negative_events": ["ui_e6", "ui_e2"],
        "gold_state_slots": {
            "remaining_accessibility_issue": "二级按钮 contrast 仍低于目标，需要重新调色",
        },
        "gold_slot_support": {
            "remaining_accessibility_issue": ["ui_e5"],
        },
        "output_slots": ["remaining_accessibility_issue"],
        "answerability": "answerable",
    },
    {
        "case_id": "ui_audit_unknown",
        "query": "最终 mobile accessibility audit 做完了吗？",
        "scope_id": "ui_accessibility",
        "operation": "state_lookup",
        "time_roles": ["planned_for", "updated_at"],
        "difficulty_tags": ["unknown_current", "plan_not_done", "cross_time_constraint"],
        "gold_events": ["ui_e8"],
        "hard_negative_events": ["ui_e4"],
        "gold_state_slots": {
            "audit_status": "只有 6 月 10 日 audit 计划，没有完成记录",
        },
        "gold_slot_support": {
            "audit_status": ["ui_e8"],
        },
        "output_slots": ["audit_status"],
        "answerability": "unknown_current",
    },
    {
        "case_id": "ui_acceptance_insufficient",
        "query": "客户验收已经完成了吗？",
        "scope_id": "ui_accessibility",
        "operation": "state_lookup",
        "time_roles": ["updated_at"],
        "difficulty_tags": ["insufficient_evidence", "answerability"],
        "gold_events": [],
        "hard_negative_events": ["ui_e4", "ui_e8"],
        "gold_state_slots": {
            "customer_acceptance": "没有足够证据确认客户验收已经完成",
        },
        "gold_slot_support": {
            "customer_acceptance": [],
        },
        "output_slots": ["customer_acceptance"],
        "answerability": "insufficient_evidence",
    },
    {
        "case_id": "api_provider_policy",
        "query": "现在回答、judge 和 Graphiti 构图分别用什么 provider？",
        "scope_id": "api_rate_limit",
        "operation": "state_summary",
        "time_roles": ["updated_at"],
        "difficulty_tags": ["multi_facet_summary", "facet_specific_validity", "branch_pivot"],
        "gold_events": ["api_e1", "api_e2", "api_e3"],
        "hard_negative_events": [],
        "gold_state_slots": {
            "answer_provider": "回答仍用 DeepSeek",
            "judge_provider": "judge 仍用 GPT",
            "graph_build_provider": "Graphiti 构图使用 OpenAI-compatible provider",
        },
        "gold_slot_support": {
            "answer_provider": ["api_e1", "api_e3"],
            "judge_provider": ["api_e1", "api_e3"],
            "graph_build_provider": ["api_e2", "api_e3"],
        },
        "output_slots": ["answer_provider", "judge_provider", "graph_build_provider"],
        "answerability": "answerable",
    },
    {
        "case_id": "api_token_status",
        "query": "OpenAI-compatible endpoint 现在还是 invalid token 吗？",
        "scope_id": "api_rate_limit",
        "operation": "state_lookup",
        "time_roles": ["updated_at"],
        "difficulty_tags": ["stale_mention_distractor", "correction_aware", "latest_event_vs_state"],
        "gold_events": ["api_e4", "api_e5"],
        "hard_negative_events": [],
        "gold_state_slots": {
            "endpoint_status": "不是；旧日志显示 invalid token，但最小 API ping 已通过，当前 endpoint 可用",
        },
        "gold_slot_support": {
            "endpoint_status": ["api_e4", "api_e5"],
        },
        "output_slots": ["endpoint_status"],
        "answerability": "answerable",
    },
    {
        "case_id": "api_rebuild_status",
        "query": "Graphiti 图重建和全量 run 做完了吗？",
        "scope_id": "api_rate_limit",
        "operation": "state_lookup",
        "time_roles": ["updated_at", "planned_for"],
        "difficulty_tags": ["plan_not_done", "latest_event_vs_state"],
        "gold_events": ["api_e6", "api_e7"],
        "hard_negative_events": ["api_e4"],
        "gold_state_slots": {
            "graphiti_run_status": "已完成；之前计划重建 Graphiti 图，之后全量 run 完成 42 个 case 并写出 repaired adapter 结果",
        },
        "gold_slot_support": {
            "graphiti_run_status": ["api_e6", "api_e7"],
        },
        "output_slots": ["graphiti_run_status"],
        "answerability": "answerable",
    },
    {
        "case_id": "api_remaining_risk",
        "query": "API 这边现在剩余风险是什么？",
        "scope_id": "api_rate_limit",
        "operation": "state_lookup",
        "time_roles": ["updated_at"],
        "difficulty_tags": ["latest_event_vs_state", "non_update_latest"],
        "gold_events": ["api_e8"],
        "hard_negative_events": ["api_e2", "api_e4"],
        "gold_state_slots": {
            "remaining_risk": "judge 调用成本和 endpoint 抖动，所以后续实验要保留 cache",
        },
        "gold_slot_support": {
            "remaining_risk": ["api_e8"],
        },
        "output_slots": ["remaining_risk"],
        "answerability": "answerable",
    },
    {
        "case_id": "api_limiter_resolution",
        "query": "DeepSeek 额度不稳定的问题现在怎么处理？",
        "scope_id": "api_rate_limit",
        "operation": "state_lookup",
        "time_roles": ["updated_at"],
        "difficulty_tags": ["branch_pivot", "facet_specific_validity"],
        "gold_events": ["api_e2", "api_e3"],
        "hard_negative_events": ["api_e5"],
        "gold_state_slots": {
            "rate_limit_resolution": "DeepSeek 仍用于回答；Graphiti 构图改用 OpenAI-compatible provider 来绕开全量构图额度不稳定",
        },
        "gold_slot_support": {
            "rate_limit_resolution": ["api_e2", "api_e3"],
        },
        "output_slots": ["rate_limit_resolution"],
        "answerability": "answerable",
    },
]


def require_unique(rows: Iterable[Mapping[str, Any]], key: str, owner: str) -> None:
    counts = Counter(str(row.get(key)) for row in rows)
    duplicates = sorted(value for value, count in counts.items() if count > 1)
    if duplicates:
        raise ValueError(f"duplicate {owner} {key}: {duplicates}")


def raw_event(row: Mapping[str, Any]) -> Dict[str, Any]:
    result = {field: row.get(field) for field in RAW_EVENT_FIELDS}
    result["source_id"] = row.get("source_id")
    result["metadata"] = dict(row.get("metadata", {}))
    return result


def event_annotation(row: Mapping[str, Any]) -> Dict[str, Any]:
    return {
        "event_id": row["event_id"],
        "updates_state": bool(row["updates_state"]),
        "event_status": row["event_status"],
        "corrects": list(row.get("corrects", [])),
        "supersedes": list(row.get("supersedes", [])),
        "notes": "Curated v1.1 expansion annotation.",
    }


def public_case(case: Mapping[str, Any]) -> Dict[str, Any]:
    stripped = {key: value for key, value in case.items() if key not in PUBLIC_CASE_FORBIDDEN_FIELDS}
    return {
        "case_id": stripped["case_id"],
        "query": stripped["query"],
        "operation": stripped["operation"],
    }


def write_public_track(v1_1_dir: Path, cases: List[Dict[str, Any]], events: List[Dict[str, Any]]) -> None:
    public_dir = v1_1_dir / "public"
    write_json(public_dir / "events.json", events)
    write_json(public_dir / "cases.json", [public_case(case) for case in cases])
    write_json(public_dir / "scope_profiles.json", build_scope_profiles(events))
    (public_dir / "README.md").write_text(
        "# STAMB-State v1.1 Public Track\n\n"
        "`events.json`, `cases.json`, and `scope_profiles.json` are the no-gold end-to-end input files.\n"
        "`scope_profiles.json` contains routing profiles derived only from public raw events.\n"
        "Evaluator-only fields are retained only in `../cases.json` and annotation files.\n",
        encoding="utf-8",
    )


def build_readme(v1_1_dir: Path, events: List[Dict[str, Any]], cases: List[Dict[str, Any]], splits: Mapping[str, List[str]]) -> str:
    answerability = Counter(str(case.get("answerability")) for case in cases)
    operations = Counter(str(case.get("operation")) for case in cases)
    tags = Counter(tag for case in cases for tag in case.get("difficulty_tags", []))
    scopes = sorted({str(event["scope_id"]) for event in events})
    lines = [
        "# STAMB-State v1.1",
        "",
        "v1.1 extends the frozen v1 benchmark without overwriting it. It keeps the same latest-valid-state retrieval task and evaluator-only gold contract, then adds harder coverage for plan-not-done, stale mentions, time-role conflicts, scope/facet collisions, and answerability.",
        "",
        "## Counts",
        "",
        f"- events: {len(events)}",
        f"- cases: {len(cases)}",
        f"- scopes: {len(scopes)}",
        f"- answerability: {dict(sorted(answerability.items()))}",
        f"- operations: {dict(sorted(operations.items()))}",
        "",
        "## Split Scopes",
        "",
    ]
    for split, split_scopes in splits.items():
        lines.append(f"- {split}: {', '.join(split_scopes)}")
    lines.extend(
        [
            "",
            "## Added Coverage",
            "",
            "- latest valid state vs latest mention",
            "- planned action without completion record",
            "- stale/invalidation/correction chains",
            "- occurred_at / mentioned_at / updated_at / planned_for / deadline_at conflicts",
            "- multi-facet summaries where only some facets changed",
            "- answerability cases for unknown current state and insufficient evidence",
            "- benchmark-bias guard cases around metric semantics",
            "",
            "## Difficulty Tags",
            "",
        ]
    )
    for tag, count in sorted(tags.items()):
        lines.append(f"- `{tag}`: {count}")
    lines.extend(
        [
            "",
            "## Files",
            "",
            "- `events_raw.json`: visible event stream without evaluator-only validity fields.",
            "- `event_annotations.json`: evaluator/oracle-only state relevance, status, correction, and supersession annotations.",
            "- `claim_annotations.json`: reserved for future claim/facet annotations.",
            "- `cases.json`: evaluator-only query cases with gold state slots and support events.",
            "- `splits.json`: scope-level train/dev/test split.",
            "- `public/`: no-gold public input generated by this builder, including raw events, public cases, and derived scope profiles.",
            "",
            "## Validation",
            "",
            "```bash",
            f"conda run -n py311 python scripts/validate_v1.py --v1-dir {v1_1_dir}",
            "conda run -n py311 python Experiment/run/run_llm_benchmark.py --data-version v1_1 --dry-run",
            "```",
        ]
    )
    return "\n".join(lines) + "\n"


def build_v1_1(source_v1_dir: Path, out_dir: Path) -> Dict[str, Any]:
    base_events = read_json(source_v1_dir / "events_raw.json")
    base_annotations = read_json(source_v1_dir / "event_annotations.json")
    base_claims = read_json(source_v1_dir / "claim_annotations.json")
    base_cases = read_json(source_v1_dir / "cases.json")
    base_splits = read_json(source_v1_dir / "splits.json")

    expansion_events = [raw_event(row) for row in EXPANSION_EVENTS]
    expansion_annotations = [event_annotation(row) for row in EXPANSION_EVENTS]
    expansion_cases = [dict(case, gold_fields_usage="evaluation_only") for case in EXPANSION_CASES]

    events = list(base_events) + expansion_events
    annotations = list(base_annotations) + expansion_annotations
    cases = list(base_cases) + expansion_cases
    claims = list(base_claims)
    splits = {split: list(scopes) + NEW_SPLIT_SCOPES.get(split, []) for split, scopes in base_splits.items()}

    require_unique(events, "event_id", "events")
    require_unique(annotations, "event_id", "event annotations")
    require_unique(cases, "case_id", "cases")

    write_json(out_dir / "events_raw.json", events)
    write_json(out_dir / "event_annotations.json", annotations)
    write_json(out_dir / "claim_annotations.json", claims)
    write_json(out_dir / "cases.json", cases)
    write_json(out_dir / "splits.json", splits)
    write_public_track(out_dir, cases, events)
    (out_dir / "README.md").write_text(build_readme(out_dir, events, cases, splits), encoding="utf-8")

    return {
        "out_dir": str(out_dir),
        "event_count": len(events),
        "case_count": len(cases),
        "scope_count": len({event["scope_id"] for event in events}),
        "added_events": len(expansion_events),
        "added_cases": len(expansion_cases),
        "splits": {split: len(scopes) for split, scopes in splits.items()},
    }


def main() -> int:
    parser = argparse.ArgumentParser(description="Build STAMB-State v1.1 by appending curated expansion cases to v1.")
    parser.add_argument("--source-v1-dir", type=Path, default=DEFAULT_V1_DIR)
    parser.add_argument("--out-dir", type=Path, default=DEFAULT_V1_1_DIR)
    args = parser.parse_args()

    summary = build_v1_1(args.source_v1_dir, args.out_dir)
    print(
        "wrote {out_dir} events={event_count} cases={case_count} scopes={scope_count} "
        "added_events={added_events} added_cases={added_cases}".format(**summary)
    )
    print(f"splits={summary['splits']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
